spring:
 application:
  name: customer
 datasource:
  url: ${url}
  username: ${username}
  password: ${password}
  driverClassName: com.mysql.jdbc.Driver
 jpa:
  show-sql: true
server: 
 port: 9093